name: quran_book
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  circle_flags: ^4.0.2
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  flutter_localization: ^0.2.0
  dio: ^5.4.1
  pin_code_fields: ^8.0.1
  quran: ^1.2.5
  provider: ^6.1.2
  riverpod: ^2.5.1
  lottie: ^3.1.0
  simple_circular_progress_bar: ^1.0.2
  animated_text_kit: ^4.2.2
  flutter_localizations:
    sdk: flutter
  sentry_flutter: ^8.9.0
  logger: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  bloc: ^8.1.4
  objectbox: ^4.0.3
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/random_pic/
    - assets/images/zikr_bcg.jpg
    - assets/images/masjid.jpg
    - assets/images/
    - assets/icons/
    - assets/images/splash_new.png
    - assets/lang/
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
