List<String> zikrNames = [
  "Qadr kechasi o'qiladigan duo",
  "Falastin\nuchun duo",
  "Laa ilaaha illalloh",
  "Salovat",
  "Astag'firulloh",
  "Subhanalloh",
  "Alhamdulillah",
  "Allohu Akbar",
  "Subhaanallohi\nva bihamdih",
  "Ya muqollubal qulub",
  "Astag'firulloh-al'aziym",
  "Sayyidul Istig'for",
  "Tonggi zikr",
  "Tungi zikr",
  "Subhanallohi\n va bihamdihi",
  "Ixlos surasi",
  "Falaq Surasi",
  "Naas Surasi",
  "Allohumma inniy\nas'alukal 'afiyata",
  "Tongi zikr 2",
  "Tingi zikr 2",
  "Allohumma 'aalimal-g'oybi",
  "Bismillahillazii\nlaa yazurru",
  "Laa ilaaha illalloh,\nvahdahu lass shariyka lah",
  "Laa havla va laa quvvata\nillaa billah",
  "Hasbunallohu va\nni'mal-vakiyl'",
  "Allohumma a'inniy\na'la zikrik",
  "Subhanalloh val-\nhamdulillah",
  "Kalima",
  "Laa ilaaha illa\n anta subhanak",
  "Oyatul Al-Kursi",
  "Fotihsa surasi",
  "Qunut duosi",
  "Robbana atina",
  "Ota onalar uchun\nqilinadigan duo",
  "Azon duosi",
  "Taroveh tasbehi",
  "Takbir tashriq"
];
